[build-system]
requires = ["setuptools>=75.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "subprober"
version = "3.0.2"
description = "Subprober - An essential HTTP multi-purpose Probing Tool for Penetration Testers and Security Researchers with Asynchronous httpx client support"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "D. Sanjai Kumar", email = "bughunterz0047@gmail.com" },
    { name = "V. Gokul", email = "th3gokul@gmail.com" }
]
keywords = ["http-probing", "pentesting", "bugbounty", "async", "httpx", "security", "subdomain", "reconnaissance"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "aiodns>=3.2.0",
    "aiofiles>=24.1.0",
    "aiojarm>=0.2.2",
    "alive_progress>=3.2.0",
    "appdirs>=1.4.4",
    "art>=6.4",
    "asynciolimiter>=1.1.1",
    "beautifulsoup4>=4.12.3",
    "bs4>=0.0.2",
    "lxml>=5.3.0",
    "colorama>=0.4.6",
    "cryptography>=44.0.0",
    "fake_useragent>=1.5.1",
    "httpx>=0.28.1",
    "mmh3>=5.0.1",
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "simhash>=2.1.2",
    "urllib3>=1.26.18",
    "uvloop>=0.21.0",
    "websockets>=14.1",
    "diskcache>=5.6.3"
]

[project.urls]
Homepage = "https://github.com/RevoltSecurities/Subprober"

[project.scripts]
subprober = "subprober.subprober:main"
