from richparser import RichParser

class CLI:
    def __init__(self):
        self.parser = None

    def cli(self):
        try:
            parser = RichParser(
                description="Subprober - An essential HTTP multi-purpose Probing Tool for Penetration Testers and Security Researchers with Asynchronous httpx client support ⚡",
                auto=False
            )

            # INPUT Section
            parser.add_argument("input", "-l", "--list", type=str,
                                help="specify the filename containing a list of URLs to probe")
            parser.add_argument("input", "-u", "--url", type=str,
                                help="specify a URL to probe and supports comma-separated values (-u google.com,https://hackerone.com)")
            parser.add_argument("input", "-resume", "--resume", type=str, default=None,
                                help="specify the resume filename generated by the subprober to continue the scan (-resume resume_Djjfos.cfg)")

            # PROBES Section
            parser.add_argument("probes", "-status-code", "--status-code", action="store_true",
                                help="display the status code of the host")
            parser.add_argument("probes", "-title", "--title", action="store_true", help="display the title of host")
            parser.add_argument("probes", "-server", "--server", action="store_true",
                                help="display the server name of the host")
            parser.add_argument("probes", "-wc", "--word-count", action="store_true",
                                help="display the HTTP response word count")
            parser.add_argument("probes", "-lc", "--line-count", action="store_true",
                                help="display the HTTP response line count")
            parser.add_argument("probes", "-cl", "--content-length", action="store_true",
                                help="display the HTTP response content length")
            parser.add_argument("probes", "-location", "--location", action="store_true",
                                help="display the redirected location of the host")
            parser.add_argument("probes", "-application-type", "--application-type", action="store_true",
                                help="display the content type of the host")
            parser.add_argument("probes", "-ip", "--ipaddress", action="store_true", help="display the IPs of the host")
            parser.add_argument("probes", "-cname", "--cname", action="store_true", help="display the CNAMEs of the host")
            parser.add_argument("probes", "-aaaa", "--aaaa-records", action="store_true",
                                help="display the AAAA records of the host")
            parser.add_argument("probes", "-htv", "--http-version", action="store_true",
                                help="display the server supported HTTP version of the host")
            parser.add_argument("probes", "-hrs", "--http-reason", action="store_true",
                                help="display the reason for HTTP connection of the host")
            parser.add_argument("probes", "-jarm", "--jarm-fingerprint", action="store_true",
                                help="display the JARM fingerprint hash of the host")
            parser.add_argument("probes", "-rpt", "--response-time", action="store_true",
                                help="display the response time for the successful request")
            parser.add_argument("probes", "-wss", "--websocket", action="store_true",
                                help="display the server supports websockets")
            parser.add_argument("probes", "-hash", "--hash", type=str,
                                help="display response body in hash format (supported hashes: md5, mmh3, simhash, sha1, sha256, sha512)")
            parser.add_argument("probes", "-dmt", "--display-method", action="store_true",
                                help="display the method of the HTTP request")
            parser.add_argument("probes", "-bp", "--body-preview", action="store_true",
                                help="display the HTTP response body in first n number of characters (default: 100)")
            parser.add_argument("probes", "-body", "--body", type=str, default=None,
                                help="post body to include in the http request and support all post body types (ex: -body 'username=admin&password=password')")
            parser.add_argument("probes", "-resolvers", "--resolvers", type=str, default="8.8.8.8,1.1.1.1",
                                help="custom DNS resolver for dns resolution and supports comma-separated (ex -resolvers 8.8.8.8,1.1.1.1)")

            # CONFIG Section
            parser.add_argument("config", "-dhp", "--disable-http-probe", action="store_true",
                                help="disable subprober from fallback to http scheme (default: disabled)")
            parser.add_argument("config", "-X", "--method", type=str,
                                choices=["get", "post", "head", "put", "delete", "patch", "trace", "connect",
                                         "options"], default="get",
                                help="request methods to probe and get response (supported: get, post, head, put, delete, patch, trace, connect, options) (default: get)")
            parser.add_argument("config", "-H", "--header", action="append",
                                help="add custom headers for probing and -H can be used multiple times to pass multiple header values (ex: -H application/json -H X-Forwarded-Host: 127.0.0.1)")
            parser.add_argument("config", "-ra", "--random-agent", action="store_true",
                                help="enable Random User-Agent to use for probing and applies same to screenshots. (default: subprober/Alpha)")
            parser.add_argument("config", "-proxy", "--proxy", type=str,
                                help="specify a proxy to send the requests through it (ex: http://127.0.0.1:8080)", default=None)
            parser.add_argument("config", "-ar", "--allow-redirect", action="store_true",
                                help="enable following redirections")
            parser.add_argument("config", "-maxr", "--max-redirection", type=int, default=10,
                                help="set max value to follow redirections (default: 10)")
            parser.add_argument("config", "-http2", "--http2", action="store_true",
                                help="enable to request with HTTP/2 support (default: Http/1.1) (info: deprecated)")
            parser.add_argument("config", "-sni", "--sni-hostname", type=str,
                                help="set custom TLS SNI host name for requests.")

            parser.add_argument("config", "-stats", "--stats",action="store_true",
                                help="show the progress stats of the subprober (info: specially for docker environments)")

            # MISCELLANEOUS Section
            parser.add_argument("miscellaneous", "-path", "--path", type=str,
                                help="specify a path or text file of paths for probing and getting results (example: -p admin.php or -p paths.txt)")
            parser.add_argument("miscellaneous", "-port", "--port", type=str,
                                help="set custom port for making HTTP request and default ports are 80,443 based on the url scheme")
            parser.add_argument("miscellaneous", "-tls", "--tls", action="store_true",
                                help="grabs the TLS data for the requested host")

            # HEADLESS Section
            parser.add_argument("headless", "-ss", "--screenshot", action="store_true",
                                help="enable to take screenshots of the page using headless browsers with asynchronous performance")
            parser.add_argument("headless", "-st", "--screenshot-timeout", type=int, default=10,
                                help="set a timeout value for taking screenshots (default: 15)")
            parser.add_argument("headless", "-scp", "--system-chrome-path", type=str, default=None,
                                help="specify the executable path of the chromedriver to use system chrome to take screenshots")
            parser.add_argument("headless", "-pdf", "--save-pdf", action="store_true",
                                help="enable to save the screenshot image in the pdf format (default: png)")
            parser.add_argument("headless", "-no-fpg", "--no-full-page", action="store_true",
                                help="disable saving screenshot in full page")
            parser.add_argument("headless", "-icb", "--include-bytes", action="store_true",
                                help="enable to include the screenshot bytes in output when json output enabled")
            parser.add_argument("headless", "-hos", "--headless-options", type=str, default=None,
                                help="set additional chrome headless browser options and supports comma-separated values (-ho \"--start-maximized\")")
            parser.add_argument("headless", "-sid", "--screenshot-idle", default=1, type=int,
                                help="set custom idle time in seconds before taking screenshots (default: 1)")
            parser.add_argument("headless", "-sp", "--screenshot-path", type=str,
                                help="specify a directory path to store screenshot results (default: currentdir/screenshots)")

            # MATCHERS Section
            parser.add_argument("matchers", "-mc", "--match-code", type=str,
                                help="match http response by specified status codes and supports comma-separated values (-mc 200,302)")
            parser.add_argument("matchers", "-mcr", "--match-code-range", type=str,
                                help="match http response by specified status code range and supports single value (-mcr 200-299)")
            parser.add_argument("matchers", "-ms", "--match-string", type=str,
                                help="match http response containing the specified string and supports comma-separated values (-ms admin,login)")
            parser.add_argument("matchers", "-mr", "--match-regex", type=str,
                                help="match http response matching the specified regex and supports comma-separated values (-mr .*admin.*,.*login.*)")
            parser.add_argument("matchers", "-mpt", "--match-path", type=str,
                                help="match http response by URL path and supports comma-separated values (-mpt /admin/wp-ajax.php,/wp-json)")
            parser.add_argument("matchers", "-ml", "--match-length", type=str,
                                help="match http response by specified response length and supports comma-separated values (-ml 1024,2048)")
            parser.add_argument("matchers", "-mlc", "--match-line-count", type=str,
                                help="match http response by specified response line count and supports comma-separated values (-mlc 10,50)")
            parser.add_argument("matchers", "-mwc", "--match-word-count", type=str,
                                help="match http response by specified word count and supports comma-separated values (-mwc 100,500)")
            parser.add_argument("matchers", "-mrt", "--match-response-time", type=float,
                                help="match http response exceeding the specified minimum response time in seconds (-mrt 2.30)")

            # FILTERS Section
            parser.add_argument("filters", "-fc", "--filter-code", type=str,
                                help="filter http response by specified status codes and supports comma-separated values (-fc 404,500)")
            parser.add_argument("filters", "-fcr", "--filter-code-range", type=str,
                                help="filter http response by specified status code range and supports single value (-fcr 400-499)")
            parser.add_argument("filters", "-fs", "--filter-string", type=str,
                                help="filter http response containing the specified string and supports comma-separated values (-fs error,not found)")
            parser.add_argument("filters", "-fr", "--filter-regex", type=str,
                                help="filter http response matching the specified regex and supports comma-separated values (-fr .*admin.*,.*login.*)")
            parser.add_argument("filters", "-fpt", "--filter-path", type=str,
                                help="filter http response by URL path and supports comma-separated values (-fpt /error,404.html)")
            parser.add_argument("filters", "-fl", "--filter-length", type=str,
                                help="filter http response by specified response length and supports comma-separated values (-fl 1024,2048)")
            parser.add_argument("filters", "-flc", "--filter-line-count", type=str,
                                help="filter http response by specified response line count and supports comma-separated values (-flc 10,50)")
            parser.add_argument("filters", "-fwc", "--filter-word-count", type=str,
                                help="filter http response by specified response word count and supports comma-separated values (-fwc 100,500)")
            parser.add_argument("filters", "-frt", "--filter-response-time", type=float,
                                help="filter http response exceeding the specified maximum response time in seconds (-frt 2.30)")

            # OUTPUT Section
            parser.add_argument("output", "-o", "--output", type=str,
                                help="define the output filename to store the results of the probing operation.")
            parser.add_argument("output", "-json", "--json", action="store_true",
                                help="store and display output in JSON format (includes only data from enabled options).")
            parser.add_argument("output", "-rdu", "--redirect-urls", action="store_true",
                                help="display the redirect URLs in the output (requires -json and -ar to enabled to enabled).")
            parser.add_argument("output", "-rdh", "--redirect-history", action="store_true",
                                help="display the full redirect history (requires -json and -ar to enabled).")
            parser.add_argument("output", "-rsc", "--redirect-status-codes", action="store_true",
                                help="display the status codes for redirections (requires -json and -ar to enabled).")
            parser.add_argument("output", "-rqh", "--request-headers", action="store_true",
                                help="include request headers in the output (requires -json and -ar to enabled).")
            parser.add_argument("output", "-rsh", "--response-headers", action="store_true",
                                help="include response headers in the output (requires -json and -ar to enabled).")
            parser.add_argument("output", "-fo", "--full-output", action="store_true",
                                help="include all available data in the output (requires -json to enabled and doesn't overrides websocket,jarm,hashes options).")

            # RATE-LIMIT Section
            parser.add_argument("rate-limit", "-c", "--concurrency", type=int, default=100,
                                help="set the concurrency level for sending http requests (default: 100)")
            parser.add_argument("rate-limit", "-rtl", "--rate-limit", type=int, default=150,
                                help="set a rate limit for sending a maximum number of requests per second (default: 1000)")

            # OPTIMIZATION Section
            parser.add_argument("optimization", "-timeout", "--timeout", type=int, default=10,
                                help="set a custom timeout value for sending requests.")
            parser.add_argument("optimization", "-delay", "--delay", type=float, default=0.5,
                                help="set a delay in seconds before sending each request (default: None)")
            parser.add_argument("optimization", "-rts", "--retries", type=int, default=0,
                                help="set a number of retries if a request fails to connect (default: 0)")

            # UPDATES Section
            parser.add_argument("updates", "-up", "--update", action="store_true",
                                help="update subprober to the latest version (uv tool required to be installed)")
            parser.add_argument("updates", "-sup", "--show-updates", action="store_true",
                                help="display the current or latest version of subprober updates")


            parser.add_argument("debug", "-silent", "--silent", action="store_true",
                                help="enable silent mode to suppress the display of Subprober banner and version information.")
            parser.add_argument("debug", "-verbose", "--verbose", action="store_true",
                                help="enable verbose mode to display error results on the console.")
            parser.add_argument("debug", "-nc", "--no-color", action="store_true",
                                help="enable to display the output without any CLI colors")
            parser.add_argument("debug", "-debug", "--debug", action="store_true", help="debug the subprober workflow")

            self.parser = parser
            return parser.parse_args()
        except KeyboardInterrupt:
            exit(1)
        except Exception as e:
            print(f"Exception occurred in the cli module due to: {e}, {type(e)}")
            exit(1)